crud/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('saveuser', views.saveUsers, name='saveuser'),
    path('getusers', views.getUsers, name='getusers'),
    path('deleteuser', views.deleteUsers, name='deleteuser'),
]

olitest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls')),
    path('', include('crud.urls')),
]

crud/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    middle_name = models.CharField(max_length=40)

crud/forms.py
from django import forms

class UserForm(forms.Form):
    uid = forms.HiddenInput()
    last_name = forms.CharField(
        label='Lastname',
        max_length=40
    )
    first_name = forms.CharField(
        label='Firstname',
        max_length=40
    )
    middle_name = forms.CharField(
        label='Middlename',
        max_length=40
    )

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

crud/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core import serializers
from .models import Users

def index(request):
    return render(request, 'crud/users.html')

def saveUsers(request):

    if request.method == 'POST':

        # process the data in request.POST as required
        uid = request.POST['uid']
        last_name = request.POST['last_name']
        first_name = request.POST['first_name']
        middle_name = request.POST['middle_name']

        if uid:
            # update data in database
            Users.objects.filter(id=uid).update(
                last_name = last_name,
                first_name = first_name,
                middle_name = middle_name
            )
        else:
            # save data to database
            Users.objects.create(
                last_name = last_name,
                first_name = first_name,
                middle_name = middle_name
            )

    return getUsers(request)

def getUsers(request):
    users = Users.objects.all()
    users = serializers.serialize('json', users)
    return HttpResponse(users, content_type='application/json')

def deleteUsers(request):
    if request.method == 'POST':
        uid = request.POST['uid']
        Users.objects.get(pk=uid).delete()

    return getUsers(request)

crud/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{% static 'node_modules/sweetalert2/dist/sweetalert2.min.css' %}">

    <title>Django Crud</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
       <span class="navbar-brand mb-0 h1">Django CRUD</span>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.18/js/dataTables.bootstrap4.min.js"></script>
    <script type="text/javascript" src="{% static 'node_modules/sweetalert2/dist/sweetalert2.min.js' %}"></script>

    {% block jsfiles %}
    {% endblock %}
  </body>
</html>

crud/templates/crud/users.html
{% extends 'base.html' %}
{% block content %}
    <br/>
    <div class="card bg-light">
        <div class="card-header"><h5 class="card-title">User Information</h5></div>
        <div class="card-body">
            <form id="frmUsers" method="post">
                {% csrf_token %}
                <input type="hidden" id="hd_id" name="hd_id" value="">
                <div class="form-row">
                    <div class="alert alert-success col-md-12" style="display: none;" role="alert"></div>

                    <div class="col-md-4 mb-3">
                        <label class="control-label"> Lastname:</label>
                        <input class="form-control" type="text" name="last_name" id="id_last_name" value="" placeholder="lastname">
                    </div>

                    <div class="col-md-4 mb-3">
                        <label class="control-label"> Firstname:</label>
                        <input class="form-control" type="text" name="first_name" id="id_first_name" value="" placeholder="firstname">
                    </div>

                    <div class="col-md-2 mb-3">
                        <label class="control-label"> Middlename:</label>
                        <input class="form-control" type="text" name="middle_name" id="id_middle_name" value="" placeholder="middlename">
                    </div>
                    <div class="col-md-1 mb-3">
                        <label for="">&nbsp;</label><br/>
                        <input id="btn_submit" class="btn btn-outline-primary btn-block" type="submit" value="Submit">
                    </div>
                    <div class="col-md-1 mb-3">
                        <label for="">&nbsp;</label><br/>
                        <button id="btn_clear" class="btn btn-outline-danger btn-block" type="button">Clear</button>
                    </div>
                </div>
            </form>
        </div>
    </div><br/>
    <div id="tcontainer"></div>
{% endblock %}

{% block jsfiles %}
    {% load static %}
    <script type="text/javascript" src="{% static 'functions.js' %}"></script>
    <script type="text/javascript" src="{% static 'users.js' %}"></script>
{% endblock %}